class LocationDefines {
  static const CHANNEL_NAME = "com.qmstudio.qmlkit.location";
}

class MethodName {
  static const ENABLE = "LOCATION_METHOD_NAME_ENABLE";
  static const REQUEST_ENABLE = "LOCATION_METHOD_NAME_REQUEST_ENABLE";
  static const HAS_PERMISSION = "LOCATION_METHOD_NAME_HAS_PERMISSION";
  static const REQUEST_PERMISSION = "LOCATION_METHOD_NAME_REQUEST_PERMISSION";
  static const GET_LOCATION = "LOCATION_METHOD_NAME_GET_LOCATION";

  static const DID_GET_LOCATION = "LOCATION_METHOD_NAME_DID_GET_LOCATION";
  static const IS_STARTED = "LOCATION_METHOD_NAME_IS_STARTED";
  static const START = "LOCATION_METHOD_NAME_START";
  static const STOP = "LOCATION_METHOD_NAME_STOP";
}
